console.log("\n\n Variable n Types \n");
console.log("heloworld");
var completed = false;
var myname = "jesteena";
var myfavcolor = "orange";
console.log(myname);
console.log(myfavcolor);
var myfullname = "jesteena baby";
var mydob = "17-may-1993";
var myage = 26;
var desc = "helooo, my name is " + myfullname + ".\n i'll be " + (myage + 1) + " years old next year ";
console.log(desc);
console.log("heloo,my name is " + myfullname + "\n i'll be " + (myage + 1) + "years old next year");
console.log("\n\n Array \n");
var myfriends = ["riya", "maya", "kp", "athira", "archu", "swathi"];
console.log(myfriends[0]);
var mymarks = [10, "twenty", "thirty", 40];
console.log(mymarks[2]);
var mymarks = [10, [11, 222, 3333, 4444], "thirty", 40];
console.log(mymarks[1][0]);
var mycoins = [20, 35, 45, 67];
console.log(mycoins[3]);
console.log("\n\n Tuple \n");
var myx;
myx = ["jesty", 26];
console.log(myx[0]);
console.log(myx[0].substr(1));
myx[0] = "niit";
console.log(myx[1].toString());
console.log("\n\n Enum \n");
var color;
(function (color) {
    color[color["red"] = 0] = "red";
    color[color["green"] = 1] = "green";
    color[color["blue"] = 2] = "blue";
})(color || (color = {}));
;
var c = color.green;
console.log(c);
